name: JSON checker

on: [push, pull_request]

jobs:
  check:
    env:
      GITHUB_REPO: ${{ github.repository }}
      GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
      EVENT: ${{ github.event_name }}
    name: Check the repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: install dependencies
      run: |
        npm install
    - name: setup
      run: |
        if [ '$EVENT' == 'pull_request' ]
        then 
            export GITHUB_REPO=LNReader/lnreader-sources
            export GITHUB_BRANCH=plugins
        fi
    - name: check
      run: |
        echo "expected github path: $GITHUB_REPO/$GITHUB_BRANCH"
        cat > check_json.js << EOF
          const plugins = require('./plugins/plugins.min.json');
          const gitPath = process.env.GITHUB_REPO+'/'+process.env.GITHUB_BRANCH;
          for(let lang in plugins) for(let plugin of plugins[lang]) if(plugin.url.indexOf(gitPath) === -1)
          throw new Error('Unexpected github path');
          console.log("Look good to me xD");
        EOF
        node check_json.js
