name: JSON checker

on: [push, pull_request]

jobs:
  check:
    env:
      GITHUB_REPO: ${{ github.repository }}
      GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
      EVENT: ${{ github.event_name }}
    name: Check the repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: install dependencies
      run: |
        npm install
    - name: setup
      run: |
        if [ $EVENT == 'pull_request' ]
        then 
            export GITHUB_REPO=LNReader/lnreader-sources
            export GITHUB_BRANCH=plugins
        fi
        [ -e .env ] && rm .env
        cp plugins/plugins.min.json plugins/current.min.json
        node scripts/json_plugins.js
    - name: check
      run: |
        cat > check_json.js << EOF
          const fs = require('fs');
          let current = JSON.stringify(JSON.parse(fs.readFileSync('plugins/current.min.json')));
          let expected = JSON.stringify(JSON.parse(fs.readFileSync('plugins/plugins.min.json')));
          if (JSON.stringify(current) === JSON.stringify(expected)){
              console.log("OK, Look good to me xD");
          }else{
              console.log("current:", current);
              console.log("expected:", expected);
              throw new Error("JSON files are not correct for this repo");
          }
        EOF
        node check_json.js
